### PR TITLE
BREAKING: Upgrade Jest to v29

### PR DESCRIPTION
**Pull request by legobeat**
#319 + #345 but rebased on `next`.

#### Blocked by
- #354
  - [ ] Release of #349

### CODE REVIEW

**Review by kasperpeulen — APPROVED** [review]
LGTM! cc @yannbf shall we release those PRs?

**Comment by kasperpeulen** [comment]
Dropping node 12 is fine, storybook itself also doesn't support node 12 anymore.

**Comment by kasperpeulen** [comment]
@legobeat Sounds good to me.

@yannbf Let's do this when you are back.

**Comment by yannbf** [comment]
Hey there! Sorry for not checking this sooner. I'll update this PR and test it out next week!

**Pull request merged**
