### PR TITLE
Feat: Support Storybook 7.0

### PR DESCRIPTION
**Pull request by IanVS**
Fixes https://github.com/storybookjs/test-runner/issues/200

This moves the Storybook core packages from `dependencies` into `peerDependencies` and opens up the the range to allow 7.0 pre-release versions.  And also adds them to `devDependencies`, and updates all the storybook devDeps to 7.0.

And it updates the example project to 7.0.

<details>
  <summary>📦 Published PR as canary version: <code>0.9.1--canary.207.e1be268.0</code></summary>
  <br />

  :sparkles: Test out this PR locally via:
  
  ```bash
  npm install @storybook/test-runner@0.9.1--canary.207.e1be268.0
  # or 
  yarn add @storybook/test-runner@0.9.1--canary.207.e1be268.0
  ```
</details>

### CODE REVIEW

**Comment by IanVS** [comment]
I changed to this canary in my project, and initially got `Cannot find module '@storybook/core-common'`.  I think this is because previously there were two different versions, so the 7.0 version got nested into `@storybook/builder-vite` rather than the top-level of `node_modules`.  Removing node_modules and the package-lock, and reinstalling solved the issue.  And now my tests run correctly.

Despite that hiccup, I think this is the correct solution, unless you want to have versions of the test-runner that support 6.x and others for 7.x, which sounds like a nightmare.

**Comment by bryanjtc** [comment]
Can this support pnpm and yarn pnp? Or it has to be on another pr? I have missing dependency errors. My workaround has been adding the dependencies directly to my package.json. Can you fix it like in other storybook packages in the main repo?

**Comment by IanVS** [comment]
@bryanjtc would you open an issue with the details of what you're seeing?

**Comment by bryanjtc** [comment]
#208 Here

**Comment by shilman** [comment]
Superseded by #210

**Pull request closed without merging**
