### PR TITLE
BREAKING: Change the eject behavior and add templates

### PR DESCRIPTION
**Pull request by bryanjtc**
### Summary
This pull request introduces significant changes across the project's configuration setup. Documentation updates provide clearer guidance for users, especially regarding ejecting configuration for more control. The restructuring of configuration and template handling in the source code, along with the introduction of new scripts and dependencies, suggests a more streamlined and modular approach to configuration management.
- Relocated the Playwright files from the `playwright` folder to the `src/templates` directory, providing a more organized structure.
- Modified the `--eject` command to enhance the functionality. Now, when using `--eject`, the template files (previously Playwright files) are also copied. Additionally, the command checks if `typescript` is installed in the project and copies the TypeScript templates accordingly. It also verifies the presence of `ts-node` as it is required by Jest to read the configuration file. If `ts-node` is not found, it is automatically added as a dev dependency.

### `tests-extended.yml` and `tests.yml`
- **Node.js Versions Updated**:
  - Added Node.js `20.x` to the testing matrix alongside `16.x` and `18.x`. 
  > Just for testing purposes. Waiting until #353 is merged.

### Workflow Step Changes in `tests.yml`
- Changed the order of steps: `yarn build` is now executed before running Jest tests.

### Command Line Options Section
- Minor wording change: "Creates local configuration files" instead of "Creates a local configuration file".

### Ejecting Configuration Section
- Expanded description for `test-storybook --eject` command. Now it includes the creation of multiple local configuration files: `test-runner-jest.config.js`, `custom-environment.js`, `global-setup.js`, `global-teardown.js`, `jest-setup.js`.

### Example Code Snippet Modified
- Simplified import statements in an example under the Accessibility Testing section.

### Jest Configuration (`jest.config.js`)
- Updated the paths in `moduleNameMapper` to point to the new `dist/templates` directory.

### Package Configuration (`package.json`)
- Removed `"playwright"` from the `"files"` array.
- Added an `"exports"` field for specifying module entry points.
- Updated the `"build"` script to include running a new script `copy-templates.ts`.
- Added new dependencies: `@types/fs-extra`, `replace-in-file`, `find-up`, `fs-extra`, `ts-node`.

### Script Changes
- New script `copy-templates.ts` for copying and modifying template files.

### Source Code (`src/*`)
- Various updates to reflect the new locations and structures of template files.
- Additional exports added to `src/index.ts`.

### Playwright Related Changes
- The `playwright` directory's contents have been moved or modified, particularly the Jest configuration and environment setup files.

## Deletions
- Removed `playwright/test-runner-jest.config.js` as it's now handled differently.

<details>
  <summary>📦 Published PR as canary version: <code>0.15.0--canary.323.da5753c.0</code></summary>
  <br />

  :sparkles: Test out this PR locally via:
  
  ```bash
  npm install @storybook/test-runner@0.15.0--canary.323.da5753c.0
  # or 
  yarn add @storybook/test-runner@0.15.0--canary.323.da5753c.0
  ```
</details>

### CODE REVIEW

**Comment by kasperpeulen** [comment]
@yannbf We probably should have a look at this one together.

**Comment by bryanjtc** [comment]
I will split this pr to separate breaking changes from non breaking changes

**Comment by yannbf** [comment]
Hey @bryanjtc! Thank you for this contribution, pretty good stuff as always!

However, I believe this doesn't align with the overall idea of the test-runner. It's supposed to be a mostly contained setup, slightly configurable by users. This PR exposes all of its internals directly to users codebases, and that breaks the idea of a contained setup. jest-playwright-preset is in maintenance mode so there are plans in the future to migrate away from it and use @playwright/test directly instead. In that situation, the more contained the test-runner is, the less disruptive this change would be for the users. I hope you understand and don't mind if I close this PR! We can always revisit this and discuss either here or on discord.

Thank you so much <3

**Comment by bryanjtc** [comment]
@yannbf If users want to customize playwright files, global-setup.js, custom-environment.js, etc, the have to manually update the node_modules folder or in the case of yarn pnp, create a patch. It seems a lot of work. That's why I think that exposing them using the eject flag should be a better option.

**Comment by yannbf** [comment]
> @yannbf If users want to customize playwright files, global-setup.js, custom-environment.js, etc, they have to manually update the node_modules folder or in the case of yarn pnp, create a patch. It seems a lot of work. That's why I think that exposing them using the eject flag should be a better option.

I see! That makes sense, but given that we will be moving away from jest-playwright-preset at some point, the less extra things we do, the easier it will be to achieve feature parity with least disruption for the users.

**Pull request closed without merging**
