### PR TITLE
Feat: Add errorMessageFormatter

### PR DESCRIPTION
**Pull request by Foxhoundn**
Closes https://github.com/storybookjs/storybook/discussions/25131

## What I did

The `errorMessageFormatter` property defines a function that will pre-format the error messages before they get reported in the CLI:

```ts
// .storybook/test-runner.ts
import type { TestRunnerConfig } from '@storybook/test-runner';

const config: TestRunnerConfig = {
  errorMessageFormatter: (message) => {
    // manipulate the error message as you like
    return message;
  },
};
export default config;
```

Here's a small example of the formatting
image

If the formatter throws an error, the test-runner will notify the user
image

#### Manual testing

_This section is mandatory for all contributions. If you believe no manual test is necessary, please state so explicitly. Thanks!_

### Documentation

- [ ] Add or update documentation reflecting your changes in this repository
- [ ] Request documentation updates in the [test-runner docs website](https://storybook.js.org/docs/writing-tests/test-runner)

## Checklist for Maintainers

- [ ] Make sure this PR contains **one** of the labels below:
   <details>
     <summary>Available labels</summary>

  - `skip-release`: Skip any releases, e.g., documentation only changes, CI config etc.
  - `patch`: Upgrade patch version (e.g. 0.0.x)
  - `minor`: Upgrade patch version (e.g. 0.x.0)
  - `major`: Upgrade patch version (e.g. x.0.0)

   </details>

### CODE REVIEW

**Comment by Foxhoundn** [comment]
@yannbf I couldn't push to your branch so had to create a sep PR

**Comment by yannbf** [comment]
Hey @Foxhoundn thanks for providing the code! I think we need to think a bit more about this since it should be a common function for errors, and right now it seems to be applied only if an exception is coming from the play function.

@kasperpeulen @shilman do you want to chime in regarding:
- functionality/behavior
- API
- naming

**Comment by Foxhoundn** [comment]
> Hey @Foxhoundn thanks for providing the code! I think we need to think a bit more about this since it should be a common function for errors, and right now it seems to be applied only if an exception is coming from the play function.
> 
> @kasperpeulen @shilman do you want to chime in regarding:
> 
> * functionality/behavior
> * API
> * naming
> 
> I would say this function should be applicable to other error events too, and receive as second argument some metadata (whenever possible) that contains at least the storyId, so users have more flexibility to know how to deal with formatting their messages.

That would be splendid - I would love to have a list of stories that failed at the end of the test run too, right now it just says 5 test suites, 25 tests. Then you have to scroll through the whole history to find those 25 tests, but it would be wonderful to have the actual story list there, for easy orientation. Something to think about?

**Review by shilman — APPROVED** [review]
It would be even better if we could fix the problem at its root and provide better error messages out of the box. But in the meantime, this change looks totally reasonable to me as a workaround. 💯

**Pull request merged**
