### PR TITLE
Support Storybook 7.0 play function exceptions

### PR DESCRIPTION
**Pull request by tmeasday**
See https://github.com/storybookjs/storybook/pull/19143

We need to ensure that stories that do not emit an `STORY_THREW_EXCEPTION` on play function error are still handled. (SBs with `hidePlayFunctionExceptions` set)

## To test:

1. Run a SB7.0 sandbox with interactions installed and a failing play function
2. `./bin/test-storybook.js --url http://localhost:6006 -i example-button.test.js`
3. Do the above with interactions removed from the SB.

@yannbf I'm not how to automate the above testing, perhaps you can give some guidance, if it's possible?

<details>
  <summary>📦 Published PR as canary version: <code>0.7.2--canary.190.e69606f.0</code></summary>
  <br />

  :sparkles: Test out this PR locally via:
  
  ```bash
  npm install @storybook/test-runner@0.7.2--canary.190.e69606f.0
  # or 
  yarn add @storybook/test-runner@0.7.2--canary.190.e69606f.0
  ```
</details>

### CODE REVIEW

**Comment by yannbf** [comment]
I'll take a look at this soon, but first, are there more changes required here? Given the new parameter that could/should be set in case it's not? @tmeasday @shilman

**Comment by tmeasday** [comment]
@yannbf, nope this should do it. There are two things that can happen from the SB side:

1. They have `throwPlayFunctionExceptions` set (the default): the SB will emit a `PLAY_FUNCTION_THREW_EXCEPTION` and and a `STORY_THREW_EXCEPTION`.

2. They have it set to `false` (using the interactions addon): the SB will emit a `PLAY_FUNCTION_EXCEPTION` and that's it.

Either way as long as we listen to both events we should be fine.

**Comment by yannbf** [comment]
> @yannbf, nope this should do it. There are two things that can happen from the SB side:
> 
> 1. They have `throwPlayFunctionExceptions` set (the default): the SB will emit a `PLAY_FUNCTION_THREW_EXCEPTION` and and a `STORY_THREW_EXCEPTION`.
> 2. They have it set to `false` (using the interactions addon): the SB will emit a `PLAY_FUNCTION_EXCEPTION` and that's it.
> 
> Either way as long as we listen to both events we should be fine.

Got it! I'll take a look at it tomorrow and check regarding the tests

**Review by yannbf — APPROVED** [review]
Thanks @tmeasday !!

**Comment by yannbf** [comment]
> @yannbf I'm not how to automate the above testing, perhaps you can give some guidance, if it's possible?

This test is already automated via the nightly check!

**Pull request merged**
