### PR TITLE
Extend hooks api with `prepare` and `getHttpHeaders` properties

### PR DESCRIPTION
**Pull request by yannbf**
Replaces #222

There are now additional properties you can set in `.storybook/test-runner.js`:

#### prepare

The test-runner has a default `prepare` function which gets the browser in the right environment before testing the stories. You can override this behavior, in case you might want to hack the behavior of the browser. For example, you might want to set a cookie, or add query parameters to the visiting URL, or do some authentication before reaching the Storybook URL. You can do that by overriding the `prepare` function.

The `prepare` function receives an object containing:

- `browserContext`: a [Playwright Browser Context](https://playwright.dev/docs/api/class-browsercontext) instance
- `page`: a [Playwright Page](https://playwright.dev/docs/api/class-page) instance.
- `testRunnerConfig`: the test runner configuration object, coming from the `.storybook/test-runner.js`.

#### getHttpHeaders

The test-runner makes a few `fetch` calls to check the status of a Storybook instance, and to get the index of the Storybook's stories. Additionally, it visits a page using Playwright. In all of these scenarios, it's possible, depending on where your Storybook is hosted, that you might need to set some HTTP headers. For example, if your Storybook is hosted behind a basic authentication, you might need to set the `Authorization` header. You can do so by passing a `getHttpHeaders` function to your test-runner config. That function receives the `url` of the fetch calls and page visits, and should return an object with the headers to be set.

```js
// .storybook/test-runner.js
module.exports = {
  getHttpHeaders: async (url) => {
    const token = url.includes('prod') ? 'XYZ' : 'ABC';
    return {
      Authorization: `Bearer ${token}`,
    };
  },
};
```

<details>
  <summary>📦 Published PR as canary version: <code>0.9.5--canary.245.714d3ca.0</code></summary>
  <br />

  :sparkles: Test out this PR locally via:
  
  ```bash
  npm install @storybook/test-runner@0.9.5--canary.245.714d3ca.0
  # or 
  yarn add @storybook/test-runner@0.9.5--canary.245.714d3ca.0
  ```
</details>

### CODE REVIEW

**Comment by yannbf** [comment]
@davidferguson the `prepare` function would allow you to achieve what you wanted in #242, and gives you much more power over it. The drawback is that you will be responsible for the behavior of preparing the browser, which might change in future releases.

**Comment by davidferguson** [comment]
Thanks @yannbf, this exactly fits our needs! Looking forward to being able to use this once it's merged.

**Review by ndelangen — APPROVED** [review]

**Comment by ndelangen** [comment]
@yannbf merge it?!

**Comment by davidferguson** [comment]
Bump, would love to see this merged at some point!

**Comment by davidferguson** [comment]
Just wanted to give this another bump!

**Comment by yannbf** [comment]
Hey @davidferguson sorry for the long time to merge this, got quite busy with the Storybook day conference!

**Pull request merged**
